name: Amplify Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.0'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Debug secrets
        run: |
          echo "GH_TOKEN: $GH_TOKEN"
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "@genflowly:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Debug .npmrc file
        run: cat ~/.npmrc

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Disable treating warnings as errors
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Build React app
        run: npm run build

      - name: Change ownership of .npm directory
        run: sudo chown -R $USER:$USER ~/.npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli@latest

      - name: Trigger Amplify Console build
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{}' "${{ secrets.AMPLIFY_WEBHOOK_URL }}"
