name: Amplify Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@genflowly'

      - name: Authenticate npm with PAT
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
          echo "@genflowly:registry=https://npm.pkg.github.com" >> ~/.npmrc
          npm config list

      - name: Check .npmrc content
        run: cat ~/.npmrc

      - name: Debug token
        run: echo "Token starts with ${NODE_AUTH_TOKEN:0:4}..."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Test GitHub Package Registry authentication
        run: |
          PACKAGE_URL="https://npm.pkg.github.com/download/@genflowly/react-assets/0.1.118/a2abe9d7d889fd61d70716a95c2ff4b5a15aa6aa"
          curl -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" $PACKAGE_URL

      - name: List packages in @genflowly scope
        run: npm list @genflowly --json

      - name: Test access to public GitHub Package
        run: npm view @actions/core

      - name: Install dependencies
        run: npm ci

      - name: Disable treating warnings as errors
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Build React app
        run: npm run build

      - name: Change ownership of .npm directory
        run: sudo chown -R $USER:$USER ~/.npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli@latest

      - name: Trigger Amplify Console build
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{}' "${{ secrets.AMPLIFY_WEBHOOK_URL }}"